name: CI
on: [push]

env:
  DIALECT: postgres
  SEQ_PORT: 26257
  SEQ_USER: root
  SEQ_PW: ''
  SEQ_DB: sequelize_test
  PATCH_MOCHA_TIMEOUT: 10000

jobs:
  seq-pg-integration-tests:
    strategy:
      matrix:
        crdb-version: [v20.2.1]
        test-path: [model]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Test ${{ matrix.test-path }} with CRDB
    steps:
      - run: docker pull cockroachdb/cockroach:v20.2.1
      - run: docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v20.2.1 start-single-node --insecure
      - run: docker exec roach bash -c 'echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: wget https://github.com/sequelize/sequelize/archive/v6.zip
      - run: unzip v6.zip -d temp-unzip-out
      - run: mv temp-unzip-out/* .downloaded-sequelize
      - run: rmdir temp-unzip-out
      - run: ls -lah .downloaded-sequelize

      - run: npm install
      - run: node sequelize_pg_tests/put-our-patches-in-downloaded-sequelize.js
      - run: ls -lah
      - run: ls -lah .downloaded-sequelize

      - run: mkdir -p .downloaded-sequelize/.cockroachdb-patches/node_modules
      - run: npm ls --prod=true --parseable=true | grep node_modules | xargs -I{} cp -r {} .downloaded-sequelize/.cockroachdb-patches/node_modules/.
      - run: cat .downloaded-sequelize/.cockroachdb-patches/index.js

      - run: mv sequelize_pg_tests/patch-mocha-each-hooks .downloaded-sequelize/.mocha-patches
      - run: ls -lah .downloaded-sequelize/.mocha-patches

      - name: Run integration tests at '${{ matrix.test-path }}'
        run: cd .downloaded-sequelize && npm ci && npm i -D pirates p-timeout && npx mocha --require .mocha-patches/register.js --timeout 10000 --reporter spec --exit "test/integration/${{ matrix.test-path }}.test.js"
