name: CI
on: [push, pull_request]

jobs:
  v20_1_8:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull cockroachdb/cockroach:v20.1.8
      - run: docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v20.1.8 start --insecure
      - run: docker exec roach bash -c 'echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure'
      - run: sleep 5
      - run: docker exec roach bash -c 'echo "\l" | cockroach sql --insecure'
  v20_2_0:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull cockroachdb/cockroach:v20.2.0
      - run: docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v20.2.0 start-single-node --insecure
      - run: docker exec roach bash -c 'echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure'
      - run: sleep 5
      - run: docker exec roach bash -c 'echo "\l" | cockroach sql --insecure'
  with-installation:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://binaries.cockroachdb.com/cockroach-v20.2.0.linux-amd64.tgz | tar zxv
      - run: sudo cp cockroach-v20.2.0.linux-amd64/cockroach /usr/local/bin/.
      - run: cockroach start-single-node --background --insecure
      - run: echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure
      - run: sleep 5
      - run: echo "\l" | cockroach sql --insecure
  should-not-work:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull cockroachdb/cockroach:v20.2.0
      - run: docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v20.2.0 start-single-node --background --insecure
      - run: docker exec roach bash -c 'echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure'
      - run: sleep 5
      - run: docker exec roach bash -c 'echo "\l" | cockroach sql --insecure'
  seq-pg-integration-tests:
    strategy:
      matrix:
        sequelize-github-ref: [v5, v6]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Pg tests from Sequelize ${{ matrix.sequelize-github-ref }}
    env:
      SEQUELIZE_GITHUB_REF: ${{ matrix.sequelize-github-ref }}
      DIALECT: postgres
      SEQ_USER: sequelize_test
      SEQ_PW: sequelize_test
      SEQ_PORT: 26257
    steps:
      - run: docker pull cockroachdb/cockroach:v20.2.0
      - run: docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v20.2.0 start-single-node --insecure
      - run: docker exec roach bash -c 'echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure'
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      -
        run: npm install
      -
        run: node sequelize_pg_tests/download-sequelize.js
      -
        run: ls -lah
        # TODO: Why no package-lock.json?????????
      -
        run: ls -lah .downloaded-sequelize
      -
        run: node sequelize_pg_tests/put-our-patches-in-downloaded-sequelize.js
      -
        run: ls -lah
      -
        run: ls -lah .downloaded-sequelize
      -
        run: mkdir -p .downloaded-sequelize/.cockroachdb-patches/node_modules
      -
        run: npm ls --prod=true --parseable=true | grep node_modules | xargs -I{} cp -r {} .downloaded-sequelize/.cockroachdb-patches/node_modules/.
      -
        run: cat .downloaded-sequelize/.cockroachdb-patches/index.js
      -
        run: echo 'require("../.cockroachdb-patches")' > .downloaded-sequelize/scripts/mocha_bootload
      -
        run: cat .downloaded-sequelize/scripts/mocha_bootload
      -
        run: cd .downloaded-sequelize && npm install && npm run test-integration
