# Copyright 2020 The Cockroach Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.

name: CI
on: [push, pull_request]

jobs:
   sequelize-postgres-integration-tests:
    # Execute Sequelize integration tests for postgres
    # This one will spawn 219 jobs
    name: (${{ matrix.sequelize-tag }}) ${{ matrix.test-path }}
    strategy:
      matrix:
        sequelize-tag: [v5.22.3]
        test-path: [associations/alias]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      DIALECT: postgres
      SEQ_PORT: 26257
      SEQ_USER: root
      SEQ_PW: ''
      SEQ_DB: sequelize_test
    steps:
      - name: Start a single CockroachDB instance (v20.2.2) with docker
        run: |
          docker pull cockroachdb/cockroach:v20.2.2
          docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:v20.2.2 start-single-node --insecure
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 26257
          docker exec roach bash -c 'echo "CREATE DATABASE sequelize_test;" | cockroach sql --insecure'

      - name: Checkout `sequelize-cockroachdb` repository
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install `sequelize-cockroachdb` dependencies
        run: npm install

      - name: Fetch Sequelize source code directly from GitHub and unzip it into `.downloaded-sequelize`
        run: |
          wget https://github.com/sequelize/sequelize/archive/${{ matrix.sequelize-tag }}.zip
          unzip ${{ matrix.sequelize-tag }}.zip -d temp-unzip-out
          mv temp-unzip-out/* .downloaded-sequelize && rmdir temp-unzip-out

      - name: Install Sequelize dependencies
        working-directory: ./.downloaded-sequelize
        run: npm install

      - name: Provide the `sequelize-cockroachdb` patches
        # This script needs `fs-jetpack` as an extra dependency
        run: |
          npm install --no-save fs-jetpack
          node .github/workflows/postgres-integration-tests-helper/put-our-patches-in-downloaded-sequelize.js
          cat .downloaded-sequelize/.cockroachdb-patches/index.js

      - name: Copy over the dependencies needed by `sequelize-cockroachdb`
        # (we use `npm ls --prod=true` to avoid copying unnecessary dev-dependencies)
        run: |
          mkdir -p .downloaded-sequelize/.cockroachdb-patches/node_modules
          npm ls --prod=true --parseable=true | grep node_modules | xargs -I{} cp -r {} .downloaded-sequelize/.cockroachdb-patches/node_modules/.

      - name: Apply an improvement to the `integration/support.js` test helper file from Sequelize
        # (this slightly helps lower the odds of a crashing test)
        run: |
          mv .github/workflows/postgres-integration-tests-helper/patch-test-integration-support.js .downloaded-sequelize/test/integration/support.js
          cat .downloaded-sequelize/test/integration/support.js

      - name: Install extra dependency for the improvement to `integration/support.js` (above)
        working-directory: ./.downloaded-sequelize
        # TODO: replace the fork tarball below with `npm install p-timeout` directly, as soon
        # as https://github.com/sindresorhus/p-timeout/pull/17 gets merged
        run: |
          npm install --no-save https://github.com/papb/p-timeout/tarball/4556add490c9e0322d2b641cf667fc90b0d63464
          node -p 'require.resolve("p-timeout")'
          node -p 'require("p-timeout").toString()'

      - name: Run integration tests at '${{ matrix.test-path }}' for Sequelize ${{ matrix.sequelize-tag }}
        working-directory: ./.downloaded-sequelize
        env:
          CLEANUP_TIMEOUT: 30000
        run: npx mocha --require ./.cockroachdb-patches/index.js --timeout 30000 --reporter spec --exit "test/integration/${{ matrix.test-path }}.test.js"
